"""Generate control-table DDL + JSON-schema FROM core.metadata (single source of truth).

Build-time tool (no Spark, no ABC). See specs/foundation/codegen-spec.md.
"""
from __future__ import annotations
import sys, json, dataclasses, datetime
from pathlib import Path
from typing import get_type_hints, get_origin, get_args, Union

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))
from core.metadata import MODELS  # noqa: E402

TABLE = {
    "SourceConfig": "cfg_source", "TargetConfig": "cfg_target", "LoadConfig": "cfg_load",
    "TransformConfig": "cfg_transform", "DQRuleConfig": "cfg_dq_rule",
    "MaskingRuleConfig": "cfg_masking_rule", "ReconRuleConfig": "cfg_recon_rule",
    "DependencyConfig": "cfg_dependency",
}
FK_MAP = {
    "cfg_load": [("source_id", "cfg_source", "source_id"), ("target_id", "cfg_target", "target_id")],
    "cfg_transform": [("source_target_id", "cfg_target", "target_id"),
                      ("destination_target_id", "cfg_target", "target_id")],
    "cfg_dq_rule": [("target_id", "cfg_target", "target_id")],
    "cfg_masking_rule": [("target_id", "cfg_target", "target_id")],
    "cfg_recon_rule": [("target_id", "cfg_target", "target_id")],
}
TYPE_MAP = {str: "STRING", bool: "BOOLEAN", int: "INT", float: "DOUBLE",
            datetime.datetime: "TIMESTAMP"}
JSON_MAP = {str: "string", bool: "boolean", int: "integer", float: "number"}


def _unwrap(t):
    if get_origin(t) is Union:
        return [a for a in get_args(t) if a is not type(None)][0]
    return t


def sql_type(t) -> str:
    o = get_origin(t)
    if o is Union:
        return sql_type(_unwrap(t))
    if o in (list,):
        return "ARRAY<STRING>"
    if o in (dict,):
        return "MAP<STRING,STRING>"
    return TYPE_MAP.get(t, "STRING")


def json_type(t) -> dict:
    o = get_origin(t)
    if o is Union:
        return json_type(_unwrap(t))
    if o in (list,):
        return {"type": "array", "items": {"type": "string"}}
    if o in (dict,):
        return {"type": "object"}
    if t is datetime.datetime:
        return {"type": "string", "format": "date-time"}
    return {"type": JSON_MAP.get(t, "string")}


def model_to_ddl(model: type) -> str:
    table = TABLE[model.__name__]
    hints = get_type_hints(model)
    fields = dataclasses.fields(model)
    pk = fields[0].name
    cols = [f"  {f.name} {sql_type(hints[f.name])}{' NOT NULL' if f.name == pk else ''}"
            for f in fields]
    cons = [f"  CONSTRAINT pk_{table} PRIMARY KEY ({pk})"]
    for fk_col, ref_t, ref_c in FK_MAP.get(table, []):
        cons.append(f"  CONSTRAINT fk_{table}_{fk_col} FOREIGN KEY ({fk_col}) "
                    f"REFERENCES insurelake_config.config.{ref_t}({ref_c})")
    body = ",\n".join(cols + cons)
    return f"CREATE TABLE IF NOT EXISTS insurelake_config.config.{table} (\n{body}\n) USING DELTA;\n"


def model_to_jsonschema(model: type) -> dict:
    hints = get_type_hints(model)
    props, required = {}, []
    for f in dataclasses.fields(model):
        props[f.name] = json_type(hints[f.name])
        if f.default is dataclasses.MISSING and f.default_factory is dataclasses.MISSING:
            required.append(f.name)
    return {"type": "object", "properties": props, "required": required,
            "additionalProperties": False}


def _render():
    header = ("-- Generated by scripts/codegen/gen_schema.py from core.metadata - DO NOT EDIT.\n\n"
              "CREATE CATALOG IF NOT EXISTS insurelake_config;\n"
              "CREATE SCHEMA  IF NOT EXISTS insurelake_config.config;\n\n")
    ddl = header + "\n".join(model_to_ddl(m) for m in MODELS)
    schema = {"$schema": "https://json-schema.org/draft/2020-12/schema",
              "$defs": {m.__name__: model_to_jsonschema(m) for m in MODELS}}
    return ddl, json.dumps(schema, indent=2) + "\n"


def generate(check: bool = False) -> int:
    ddl, schema = _render()
    ddl_p = REPO / "conf/ddl/control_tables.sql"
    schema_p = REPO / "conf/metadata/_schema.json"
    if check:
        stale = [str(p) for p, c in ((ddl_p, ddl), (schema_p, schema))
                 if not p.exists() or p.read_text() != c]
        if stale:
            print("STALE (run gen_schema.py):", stale)
            return 1
        print("up to date")
        return 0
    ddl_p.write_text(ddl)
    schema_p.write_text(schema)
    print(f"wrote {ddl_p.relative_to(REPO)} and {schema_p.relative_to(REPO)}")
    return 0


def main(argv: list | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    try:
        return generate(check="--check" in argv)
    except Exception as e:  # build-time tool: clear failure, no ABC
        print("codegen error:", e)
        return 2


if __name__ == "__main__":
    sys.exit(main())
